### ISSUE TITLE
hello help plz

### ISSUE THREAD

**Issue by Tonpozzi** [xtekky/x-reporter#34]
Traceback (most recent call last):
  File "C:\Users\maima\Downloads\TikTok-Report-Bot-main (1)\TikTok-Report-Bot-main\main.py", line 60, in <module>
    TikReport(cookies).start(username)
  File "C:\Users\maima\Downloads\TikTok-Report-Bot-main (1)\TikTok-Report-Bot-main\main.py", line 47, in start
    this.userInfo = Api(cookies = this.cookies).user_info(username).json()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maima\Downloads\TikTok-Report-Bot-main (1)\TikTok-Report-Bot-main\utils\api.py", line 111, in user_info
    return this.client.get(f'https://www.tiktok.com/api/user/detail/?{this.sign(params, this.userAgent)}', headers = this.get_headers(), cookies = this.cookies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maima\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\tls_client\sessions.py", line 422, in get
    return self.execute_request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maima\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\tls_client\sessions.py", line 405, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: json: cannot unmarshal object into Go struct field RequestInput.headers of type string

**Comment by Sechsmio1587** [comment]
did you fix it?
